steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - fitbit-heart-rate-ingestion-daily
  - --region=europe-west2
  - --source=.
  - --trigger-http
  - --runtime=python310
  dir: "heart-rate-ingestion"